const canvas=document.querySelector('#game');
const ctx=canvas.getContext('2d',{alpha:true});ctx.imageSmoothingEnabled=false;
const ui={chapter:document.querySelector('#chapter'),objective:document.querySelector('#objective'),hint:document.querySelector('#hint'),dialogue:document.querySelector('#dialogue'),portrait:document.querySelector('#portrait'),speaker:document.querySelector('#speaker'),line:document.querySelector('#line'),toast:document.querySelector('#toast'),overlay:document.querySelector('#overlayScene'),pause:document.querySelector('#pause'),ending:document.querySelector('#endingCard'),stage:document.querySelector('#stage')};
const files={
 apartment:'./asserts/apartment.png',celebration:'./asserts/celebration.png',
 portraitHome:'./asserts/portrait-vladimir.png',portraitDasha:'./asserts/portrait-dasha.png',portraitSasha:'./asserts/portrait-sasha.png',portraitTimoha:'./asserts/portrait-timoha.png',
 street:'./asserts/street.jpg',car:'./asserts/car.jpg',building:'./asserts/building.jpg',lobby:'./asserts/lobby.jpg',hall:'./asserts/hall.jpg',office:'./asserts/office.jpg',class:'./asserts/class.jpg',notification:'./asserts/notification.jpg',message:'./asserts/message.jpg',reply:'./asserts/reply.jpg',desktop:'./asserts/desktop.jpg',explorer:'./asserts/explorer.jpg',
 vladimirBack:'./asserts/vladimir-back.png',vladimirSide:'./asserts/vladimir-side.png',vladimirRight:'./asserts/vladimir-right.png'
};
const imgs={};for(const [key,path] of Object.entries(files)){const im=new Image();im.decoding='async';im.src=path;imgs[key]=im;}

for(const [key,im] of Object.entries(imgs)){im.addEventListener('error',()=>console.error('Не удалось загрузить изображение:',key));}
Promise.all(Object.values(imgs).map(im=>im.decode?im.decode().catch(()=>{}):Promise.resolve())).then(()=>{document.documentElement.classList.add('assets-ready');});
const portraits={'Владимир Иванович':'portraitHome','Даша':'portraitDasha','Варя':'portraitDasha','Тимоха':'portraitTimoha','Саша Раев':'portraitSasha'};
let scene='home',route='stairs',player={x:92,y:273,face:1,dx:0,dy:0},keys=new Set(),dialog=null,paused=false,gameOver=false,endingReady=false,drive={progress:0,speed:0,x:320,y:278,traffic:[],spawn:0,lastCrash:0,shake:0},clock=0,lastFrame=0,pickupUntil=0,confettiParts=[];
function setChapter(text,objective){ui.chapter.textContent=text;ui.objective.textContent=objective;}
function talk(lines,done=()=>{}){keys.clear();dialog={lines,index:0,done};ui.dialogue.hidden=false;paintDialogue();}
function paintDialogue(){if(!dialog)return;const line=dialog.lines[dialog.index];ui.speaker.textContent=line.speaker;ui.line.textContent=line.text;const src=files[portraits[line.speaker]||'portraitHome'];ui.portrait.src=src;ui.portrait.alt=line.speaker;}
function advance(){if(!dialog)return;dialog.index++;if(dialog.index>=dialog.lines.length){const done=dialog.done;dialog=null;ui.dialogue.hidden=true;done();return;}paintDialogue();}
function line(speaker,text){return {speaker,text};}
let toastTimer=0;function toast(text,ms=1400){ui.toast.textContent=text;ui.toast.classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>ui.toast.classList.remove('on'),ms);}
function visual(key,label='',full=false){ui.overlay.innerHTML='';ui.overlay.classList.toggle('full',full);if(label){const title=document.createElement('div');title.className='overlay-label';title.textContent=label;ui.overlay.append(title);}const image=document.createElement('img');image.src=files[key]||'';image.alt=label;ui.overlay.append(image);ui.overlay.hidden=false;}
function hideVisual(){ui.overlay.hidden=true;ui.overlay.innerHTML='';ui.overlay.classList.remove('full');}
function changeScene(name,x=85,y=270){scene=name;player={x,y,face:1,dx:0,dy:0};keys.clear();hideVisual();ui.ending.hidden=true;endingReady=false;}
function object(){switch(scene){case'home':return {x:585,y:222,label:'Выйти из дома'};case'street':return {x:428,y:224,label:'Сесть в машину'};case'outside':return {x:335,y:237,label:'Войти в МИФИ'};case'lobby':return {x:315,y:267,label:'В коридор'};case'hall':return route==='stairs'?{x:578,y:198,label:'Подняться на 4 этаж'}:route==='404'?{x:350,y:192,label:'Войти в кабинет 404'}:{x:573,y:198,label:'Вернуться в кабинет 407'};case'floor4':return {x:484,y:185,label:'Войти в кабинет 407'};case'officeMsg':return {x:424,y:241,label:'Прочитать сообщение'};case'room404':return pickupUntil>clock?null:{x:388,y:281,label:'Взять флешку'};case'officeReturn':return {x:388,y:198,label:'Открыть компьютер'};default:return null;}}
function currentBackdrop(){if(scene==='home')return'apartment';if(scene==='street')return'street';if(scene==='outside')return'building';if(scene==='lobby')return'lobby';if(scene==='hall')return'hall';if(scene==='floor4'||scene==='officeMsg'||scene==='officeReturn')return'office';if(scene==='class'||scene==='room404')return'class';return null;}
function centerCover(im){const scale=Math.max(640/im.width,360/im.height);const w=im.width*scale,h=im.height*scale;ctx.drawImage(im,(640-w)/2,(360-h)/2,w,h);}
function px(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h));}
function character(x,y,scale=1,coat='#273343',face=1,phase=0,crouch=false){const s=scale,step=Math.sin(phase*10)*2*s,base=crouch?4*s:0;ctx.fillStyle='#1b2022';ctx.fillRect(x-12*s,y-3*s,24*s,5*s);px(x-6*s,y-30*s+base,12*s,11*s,'#efbd99');px(x-7*s,y-34*s+base,14*s,7*s,'#493126');px(x-9*s,y-26*s+base,3*s,4*s,'#efbd99');px(x+6*s,y-26*s+base,3*s,4*s,'#efbd99');px(x-5*s,y-23*s+base,2*s,2*s,'#28333b');px(x+3*s,y-23*s+base,2*s,2*s,'#28333b');px(x-9*s,y-19*s+base,18*s,16*s,coat);px(x-7*s,y-4*s+base,5*s,5*s,'#303746');px(x+2*s,y-4*s+base,5*s,5*s,'#303746');px(x-7*s+step,y+1*s,5*s,9*s,'#32303a');px(x+2*s-step,y+1*s,5*s,9*s,'#32303a');px(x-9*s+step,y+8*s,7*s,3*s,'#171a20');px(x+1*s-step,y+8*s,8*s,3*s,'#171a20');if(crouch){px(x+8*s,y-12*s,9*s,3*s,'#efbd99');}}
function drawCharacterSprite(x,y,scale=0.23,face=1){
  // Dedicated art per heading: walking up = back view №20, walking left = side view №21
  // (already facing left), walking right = mirrored side view vladimir-right.png.
  const key=player.dy<0?'vladimirBack':player.dx<0?'vladimirSide':player.dx>0?'vladimirRight':'vladimirBack';
  const im=imgs[key];
  if(!im||!im.complete||!im.naturalWidth)return;
  const h=92*scale/0.23, w=im.naturalWidth*(h/im.naturalHeight);
  ctx.drawImage(im,x-w/2,y-h+4,w,h);
}
function drawCar(x,y,color='#397cb8',scale=1){const s=scale;px(x-11*s,y-19*s,22*s,38*s,'#14232e');px(x-9*s,y-17*s,18*s,34*s,color);px(x-7*s,y-10*s,14*s,9*s,'#a8ccd0');px(x-7*s,y+3*s,14*s,8*s,'#1d3340');px(x-7*s,y-17*s,4*s,3*s,'#ffe39a');px(x+3*s,y-17*s,4*s,3*s,'#ffe39a');px(x-13*s,y-12*s,3*s,8*s,'#11161b');px(x+10*s,y-12*s,3*s,8*s,'#11161b');px(x-13*s,y+9*s,3*s,8*s,'#11161b');px(x+10*s,y+9*s,3*s,8*s,'#11161b');px(x-7*s,y+15*s,4*s,2*s,'#ff6a58');px(x+3*s,y+15*s,4*s,2*s,'#ff6a58');}
function drawRoad(dt){px(0,0,640,360,'#719c50');let offset=(drive.progress*2)%72;for(let y=-72+offset;y<390;y+=75){px(30,y,28,26,'#437843');px(34,y-5,20,15,'#62934a');px(584,y+16,28,29,'#437843');px(588,y+9,19,18,'#719950');px(78,y+40,7,8,'#b99a66');px(555,y+52,8,8,'#cfb978');}px(125,0,390,360,'#696f69');px(134,0,372,360,'#39464b');px(139,0,362,360,'#46545a');px(313,0,4,360,'#e4d181');px(316,0,2,360,'#88784d');for(let y=-52+offset;y<400;y+=58){px(238,y,4,30,'#e8e8ce');px(398,y,4,30,'#e8e8ce');}for(let y=-46+offset;y<400;y+=119){px(124,y,11,18,'#ddd2b1');px(503,y+30,7,13,'#c6a35d');}ctx.fillStyle='#192026';ctx.font='bold 11px monospace';ctx.fillText('МИФИ  →',25,29);ctx.fillStyle='#f1d88f';ctx.fillText(Math.min(100,Math.floor(drive.progress/16))+'%',563,31);
 const dtSafe=Math.min(dt,.04);drive.spawn-=dtSafe;if(drive.spawn<=0){const lane=[198,280,365,448][Math.floor(Math.random()*4)];drive.traffic.push({x:lane,y:-34,color:['#93aa47','#cf7657','#bac1b4','#d5a34f'][Math.floor(Math.random()*4)],speed:.64+Math.random()*.32});drive.spawn=1.15+Math.random()*.65;}for(const car of drive.traffic){car.y+= (125*car.speed+drive.speed*22)*dtSafe;drawCar(car.x,car.y,car.color,.8);if(Math.abs(car.x-drive.x)<23&&Math.abs(car.y-drive.y)<40&&clock-drive.lastCrash>1.6){drive.lastCrash=clock;drive.shake=.24;drive.progress=Math.max(0,drive.progress-22);drive.x+=drive.x<car.x?-37:37;toast('Ай! Аккуратнее!',1450);tone(110,.12,'square');} }drive.traffic=drive.traffic.filter(c=>c.y<410);drawCar(drive.x,drive.y,'#326fbd',1.05);}
function draw(){const dt=Math.min(clock-lastFrame,.04)||0;lastFrame=clock;ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,640,360);
 if(scene==='desktop'){const im=imgs.desktop;if(im.complete&&im.naturalWidth)ctx.drawImage(im,0,0,640,360);return;}
 if(scene==='explorer'||scene==='desktop'){const im=imgs[scene];if(im.complete&&im.naturalWidth)ctx.drawImage(im,0,0,640,360);if(scene==='explorer'&&!dialog){setChapter('Неизвестная флешка','Откройте папку «Любимому куратору Володе»');ui.hint.textContent='[E] Открыть папку «Любимому куратору Володе»';ui.hint.classList.add('on');}else{ui.hint.classList.remove('on');}return;}
 if(scene==='ending'){const im=imgs.celebration;if(im.complete&&im.naturalWidth)centerCover(im);for(const p of confettiParts){p.y+=p.v*dt;if(p.y>360){p.y=-5;p.x=Math.random()*640;}p.x+=Math.sin(clock*2+p.s)*.35;px(p.x,p.y,p.s,p.s*2,p.c);}return;}
 if(scene==='drive'){ui.hint.classList.remove('on');if(drive.shake>0){drive.shake-=dt;ctx.save();ctx.translate((Math.random()-.5)*5,(Math.random()-.5)*4);}drawRoad(dt);if(drive.shake>0)ctx.restore();drive.progress+=drive.speed*dt*62;if(keys.has('ArrowUp')||keys.has('KeyW'))drive.speed=Math.min(1.5,drive.speed+dt*.92);else drive.speed=Math.max(.48,drive.speed-dt*.2);if(keys.has('ArrowDown')||keys.has('KeyS'))drive.speed=Math.max(.22,drive.speed-dt*1.6);if(keys.has('ArrowLeft')||keys.has('KeyA'))drive.x-=dt*155;if(keys.has('ArrowRight')||keys.has('KeyD'))drive.x+=dt*155;drive.x=Math.max(163,Math.min(477,drive.x));if(drive.progress>=1600){scene='outside';player={x:91,y:270,face:1,dx:0,dy:0};drive.traffic=[];drive.progress=0;toast('Вы приехали!',1800);setChapter('У входа в МИФИ','Подойдите ко входу');}return;}
 const bg=currentBackdrop(),im=bg&&imgs[bg];if(im?.complete&&im.naturalWidth)centerCover(im);else px(0,0,640,360,'#283748');
 // Small scene-specific details make the still reference art part of a playable space.
 if(scene==='street'){const c=imgs.car;if(c.complete&&c.naturalWidth){ctx.imageSmoothingEnabled=true;ctx.drawImage(c,c.naturalWidth*.6359,c.naturalHeight*.4736,c.naturalWidth*.1648,c.naturalHeight*.1687,382,174,96,45);ctx.imageSmoothingEnabled=false;}}
 if(scene==='hall'){px(555,155,49,24,'#385347');ctx.fillStyle='#e5e1c7';ctx.font='bold 9px monospace';ctx.fillText('ЛЕСТНИЦА ↑',559,171);if(route==='404'||route==='return'){px(314,149,45,25,'#785444');ctx.fillStyle='#fff0c5';ctx.font='bold 9px monospace';ctx.fillText(route==='404'?'404':'407',324,166);}}
 if(scene==='floor4'){px(456,148,49,28,'#69513f');ctx.fillStyle='#ffe6ae';ctx.font='bold 9px monospace';ctx.fillText('407',474,166);}
 if(scene==='room404'&&clock%1.2<.7&&pickupUntil<clock){px(380,280,17,5,'#f2d87d');px(382,279,12,2,'#fff4bf');}
 if(scene==='class'){const students=[[115,244,'#242a30'],[159,244,'#684c45'],[237,240,'#8c735f'],[278,240,'#292d34'],[114,293,'#62504b'],[162,293,'#30353a'],[238,292,'#54443d'],[280,292,'#825c4f'],[347,244,'#2e3037'],[391,244,'#805f4c'],[467,242,'#2d3339'],[510,242,'#674c46']];for(let i=0;i<students.length;i++){const [x,y,c]=students[i];character(x,y,.77,c,1,clock+(i%3)*.4);if(i%2===0&&clock%2<1.15)px(x+9,y-16,4,2,'#f5e6c7');}ctx.fillStyle='#e9e3c7';ctx.font='bold 9px monospace';ctx.fillText('Проектирование информационных систем',230,92);px(232,98,188,2,'#7bab7d');if(clock%6<.7){ctx.fillStyle='#f4c972';ctx.font='bold 9px monospace';ctx.fillText('♪ ха-ха',520,72);}}
 if(scene==='room404'&&pickupUntil>clock){drawCharacterSprite(player.x,player.y,.23,player.face);}else drawCharacterSprite(player.x,player.y,.23,player.face);
 const obj=object(),near=obj&&Math.hypot(obj.x-player.x,obj.y-player.y)<54&&!dialog&&!paused;ui.hint.textContent=near?'[E] '+obj.label:'';ui.hint.classList.toggle('on',Boolean(near));
 if(scene==='home')setChapter('Квартира · 08:10','Пора на работу');else if(scene==='street')setChapter('Улица · машина рядом','Подойдите к машине');else if(scene==='outside')setChapter('МИФИ · главный вход','Войдите в здание');else if(scene==='lobby')setChapter('Первый этаж','Найдите коридор');else if(scene==='hall')setChapter(route==='stairs'?'Коридор · первый этаж':route==='404'?'Коридор · кабинет 404':'Коридор · кабинет 407',route==='stairs'?'Найдите лестницу на четвёртый этаж':'Найдите нужный кабинет');else if(scene==='floor4')setChapter('Четвёртый этаж','Войдите в кабинет 407');else if(scene==='officeMsg')setChapter('Кабинет 407','Телефон на столе');else if(scene==='room404')setChapter('Кабинет 404','Поищите флешку у кафедры');else if(scene==='officeReturn')setChapter('Кабинет 407','Подойдите к компьютеру');
}
function tone(freq=440,duration=.07,type='sine'){try{const ac=tone.ac||(tone.ac=new AudioContext()),o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.045,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+duration);o.connect(g);g.connect(ac.destination);o.start();o.stop(ac.currentTime+duration);}catch{}}
function enterRoom(){changeScene('office',85,270);setChapter('Кабинет 407','');talk([line('Владимир Иванович','Так, пара в Л_207а... мои исики.')],()=>{toast('Некоторое время спустя...',2100);setTimeout(()=>talk([line('Владимир Иванович','Время идти на пару.')],()=>startClass()),2150);});}
function startClass(){changeScene('class',78,256);setChapter('Аудитория · занятие началось','Лекция по проектированию информационных систем');talk([
 line('Владимир Иванович','Доброе утро, коллеги.'),
 line('Владимир Иванович','Ну что, расскажите, что предложите, ой подождите.'),
 line('Владимир Иванович','Даша, подойди сюда.'),
 line('Даша','Да?'),
 line('Владимир Иванович','На тебе карточку, купи мне как обычно.'),
 line('Даша','Хорошо, Владимир Иванович.'),
 line('Владимир Иванович','Итак, сегодня проектируем информационные системы. Открываем тетради.'),
 line('Владимир Иванович','Варя, не списывай у Федора.'),
 line('Варя','Да блин.'),
 line('Владимир Иванович','Тим, ну сколько можно, что это за «я упала с сеновала, тормозила головой», ты когда чёлочку подравняешь.'),
 line('Владимир Иванович','Вы, конечно, группа Семикина, на коне, вам всё можно, но всё же.'),
 line('Владимир Иванович','Так, а во сколько у нас пара-то кончается?'),
 line('Саша Раев','Ой, а вы можете меня отпустить в 13:40 пораньше?'),
 line('Владимир Иванович','Хорошо, я тебя отпущу в 13:40, а группа уйдёт в 13:10.'),
 line('Владимир Иванович','Да кто там ноги пораставлял свои под моей партой, а?'),
 line('Тимоха','Нооормально.')
 ],()=>{toast('Дзынь! Перемена',1900);setTimeout(()=>{changeScene('officeMsg',83,272);toast('Спустя некоторое время...',1800);setTimeout(()=>setChapter('Кабинет 407','Телефон на столе'),1850);},2050);});}
function messageScene(){visual('notification','НОВОЕ СООБЩЕНИЕ · MAX');tone(680,.08);setTimeout(()=>{visual('message','ПЕРЕПИСКА · ВАРЯ');talk([line('Варя','Владимир Иванович, у вас там пара следующая в 404, а я там флешку 2 пары назад ОПЯТЬ забыла, сможете посмотреть пожалуйста?')],()=>{talk([line('Владимир Иванович','По объявлению...')],()=>talk([line('Владимир Иванович','Хорошо.')],()=>{visual('reply','ОТВЕТ ОТПРАВЛЕН');setTimeout(()=>{hideVisual();route='404';changeScene('hall',85,270);setChapter('Коридор · кабинет 404','Найдите кабинет 404');},1100);}));});},900);}
function pickUp(){pickupUntil=clock+1.05;tone(720,.06);setTimeout(()=>{route='return';changeScene('hall',530,270);setChapter('Коридор · обратно','Вернитесь в кабинет 407');toast('Флешка найдена',1100);},900);}
function openComputer(){changeScene('desktop');visual('desktop','КОМПЬЮТЕР · WINDOWS 7',true);talk([line('Владимир Иванович','Так, где моя флешка.')],()=>{hideVisual();scene='explorer';visual('explorer','USB-НАКОПИТЕЛЬ (E:) · НАЙДЕНА ПАПКА',true);talk([line('Владимир Иванович','Ой блин, опять всё путаю, ну ладно, посмотрю что там у неё.')],()=>setChapter('Неизвестная флешка','Откройте папку «Любимому куратору Володе»'));});}
function finale(){hideVisual();scene='ending';ui.stage.classList.add('ending-flash');setTimeout(()=>ui.stage.classList.remove('ending-flash'),700);const im=imgs.celebration;if(im.complete&&im.naturalWidth)centerCover(im);ui.ending.hidden=true;endingReady=false;setChapter('Секретный подарок','');confettiParts=Array.from({length:100},()=>({x:Math.random()*640,y:-Math.random()*360,v:35+Math.random()*100,c:['#ffe071','#ff7d9b','#76e4df','#faf2c8'][Math.floor(Math.random()*4)],s:2+Math.random()*3}));talk([line('Владимир Иванович','А вот оно что...'),line('Владимир Иванович','Вот вы какие...'),line('Владимир Иванович','Спасибо, ребята.')],()=>{endingReady=true;ui.ending.hidden=false;setChapter('С Днём СПО!','');});}
function interact(){if(dialog){advance();tone(460,.035);return;}if(scene==='drive')return;if(scene==='explorer'){finale();tone(850,.1);return;}if(scene==='desktop'){openComputer();return;}if(scene==='ending')return;const obj=object();if(!obj||Math.hypot(obj.x-player.x,obj.y-player.y)>58)return;tone(540,.055);
 if(scene==='home'){toast('До скорого, квартира!',700);setTimeout(()=>{changeScene('street',104,277);setChapter('Улица · машина рядом','Подойдите к машине');},550);}
 else if(scene==='street'){scene='drive';drive={progress:0,speed:.45,x:320,y:279,traffic:[],spawn:.9,lastCrash:0,shake:0};setChapter('Дорога до МИФИ','↑ газ · ← → объезжайте машины');}
 else if(scene==='outside'){talk([line('Владимир Иванович','Ну, приехали.')],()=>{changeScene('lobby',88,273);setChapter('Первый этаж','Найдите проход в коридор');});}
 else if(scene==='lobby'){changeScene('hall',80,270);route='stairs';}
 else if(scene==='hall'&&route==='stairs'){talk([line('Владимир Иванович','Четвёртый этаж. Кабинет 407.')],()=>changeScene('floor4',86,273));}
 else if(scene==='floor4'){enterRoom();}
 else if(scene==='officeMsg'){messageScene();}
 else if(scene==='hall'&&route==='404'){changeScene('room404',78,270);}
 else if(scene==='room404'){pickUp();}
 else if(scene==='hall'&&route==='return'){enterReturnOffice();}
 else if(scene==='officeReturn'){openComputer();}
}
function enterReturnOffice(){changeScene('officeReturn',90,270);setChapter('Кабинет 407','Подойдите к компьютеру');}
function reset(){scene='home';route='stairs';player={x:92,y:273,face:1,dx:0,dy:0};keys.clear();dialog=null;paused=false;gameOver=false;endingReady=false;drive={progress:0,speed:0,x:320,y:278,traffic:[],spawn:0,lastCrash:0,shake:0};ui.pause.hidden=true;ui.ending.hidden=true;ui.dialogue.hidden=true;hideVisual();talk([line('Владимир Иванович','Ну что... пора на работу.')]);setChapter('Квартира · 08:10','Подойдите к двери');}
function togglePause(){if(scene==='ending'&&endingReady)return;paused=!paused;ui.pause.hidden=!paused;if(paused)keys.clear();}
function keyName(e){if(e.code==='Space')return'Space';if(e.code==='Enter')return'Enter';if(e.code==='Escape')return'Escape';if(e.code==='ArrowUp')return'ArrowUp';if(e.code==='ArrowDown')return'ArrowDown';if(e.code==='ArrowLeft')return'ArrowLeft';if(e.code==='ArrowRight')return'ArrowRight';if(/^Key[WASD]$/.test(e.code))return e.code;return e.code;}
window.addEventListener('keydown',e=>{const k=keyName(e);if(e.repeat&&['Enter','Space','KeyE','Escape'].includes(k))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyW','KeyA','KeyS','KeyD','KeyE'].includes(k))e.preventDefault();if(k==='Escape'){togglePause();return;}if(paused)return;if(['Enter','Space'].includes(k)){if(dialog)advance();return;}if(k==='KeyE'){interact();return;}keys.add(k);});window.addEventListener('keyup',e=>keys.delete(keyName(e)));window.addEventListener('blur',()=>keys.clear());
ui.dialogue.addEventListener('click',e=>{if(e.target.closest('button'))return;advance();});ui.stage.addEventListener('pointerdown',e=>{if(scene!=='explorer'||dialog)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*640/r.width,y=(e.clientY-r.top)*360/r.height;if(x>125&&x<405&&y>85&&y<150)interact();});
document.querySelector('#menuButton').addEventListener('click',togglePause);document.querySelector('#resumeButton').addEventListener('click',togglePause);document.querySelector('#restartButton').addEventListener('click',reset);document.querySelector('#againButton').addEventListener('click',reset);
function tick(now){clock=now/1000;let dx=0,dy=0;if(!paused&&!dialog&&scene!=='drive'&&scene!=='desktop'&&scene!=='explorer'&&scene!=='ending'){if(keys.has('ArrowLeft')||keys.has('KeyA'))dx--;if(keys.has('ArrowRight')||keys.has('KeyD'))dx++;if(keys.has('ArrowUp')||keys.has('KeyW'))dy--;if(keys.has('ArrowDown')||keys.has('KeyS'))dy++;if(dx||dy){player.dy=dy;player.dx=dx;const n=Math.hypot(dx,dy);player.x+=dx/n*105/60;player.y+=dy/n*86/60;player.x=Math.max(27,Math.min(613,player.x));player.y=Math.max(145,Math.min(319,player.y));if(dx)player.face=Math.sign(dx);}}
 if(!dx&&!dy){player.dy=0;player.dx=0;}if(!paused)draw();requestAnimationFrame(tick);}requestAnimationFrame(tick);reset();
